// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Content   string     `json:"content"`
	AuthorID  string     `json:"authorID"`
	CreatedAt time.Time  `json:"createdAt"`
	Children  []*Comment `json:"children"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Content  string  `json:"content"`
	AuthorID string  `json:"authorID"`
}

type NewPost struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	AuthorID        string `json:"authorID"`
	CommentsEnabled *bool  `json:"commentsEnabled,omitempty"`
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	AuthorID        string     `json:"authorID"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	CreatedAt       time.Time  `json:"createdAt"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
